### ISSUE TITLE
Site http://ui.hawt.io doesn't open on IE11

### ISSUE THREAD

**Issue by abkieling** [hawtio/hawtio-ui#18]
A blank page is shown when we access http://ui.hawt.io using IE11.

Message in the console:
SCRIPT445: Object doesn't support this action
File: hawtio-core-navigation.js, Line: 104, Column: 9

**Comment by gashcrumb** [comment]
Ah yeah, looks like I need to add a dispatchEvent polyfill so the custom event stuff works in hawtio-core-navigation on IE11...  Thanks for catching that!

**Comment by abkieling** [comment]
IE11 doesn't support String.prototype.startsWith(). We can use lodash, add a polyfill, or avoid using it. Any preference?

**Comment by gashcrumb** [comment]
Ah, some leftover cruft from removing sugarjs.  I'd probably just replace
that with lodash or just use .indexof().
