### ISSUE TITLE
allow ascending/descending to be specified on a column's default sort order in simple data table

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-ui#2]

**Comment by abkieling** [comment]
@jstrachan , do you mean you would like to add an optional "ascending=true|false" property to the "columnDefs" items, so when the user clicks on the column header, we use that property to sort the data?

**Comment by abkieling** [comment]
@jstrachan , sorting isn't working on the Name, City, and Twitter columns of the hawtio-simple-table example. What's missing?

**Comment by jstrachan** [comment]
@alexkieling yeah - it'd be nice to specify the ascending=true/false on the columnDefs.

You're right the test table is a bit broken from a sorting perspective; also reverse sorting doesn't seem to work! Looks like something's a bit broken with the sorting!
