### ISSUE TITLE
hawtio-simple-table: 'select all' checkbox is selecting filtered out rows

### ISSUE THREAD

**Issue by abkieling** [hawtio/hawtio-ui#21]
Rows filtered out from the table using a filter box are selected when the user clicks on the header 'select all' checkbox. It should select only the currently visible rows on the table. This is an issue, right? I can work on it.

**Comment by gashcrumb** [comment]
Yeah, I agree, it's odd to have hidden stuff selected, and could definitely confuse folks working with a view...
