### ISSUE TITLE
Document the simple table configuration options

### ISSUE THREAD

**Issue by abkieling** [hawtio/hawtio-ui#26]
It would be great to have a table somewhere documenting all the possible configuration options for the hawtio simple table.

**Comment by abkieling** [comment]
I could work on this one. Where should this type of documentation go?

**Comment by gashcrumb** [comment]
Agreed!

It'd be really nice to maybe do something like we've done with the forms plugin with live examples, for example:

http://forms.hawt.io/forms2/selector_example?main-tab=hawtio-forms2-tests-form2&sub-tab=hawtio-forms2-tests-form2-simple_example

So then it'd just be a matter of updating the test/sample controller and related page(s)

**Comment by gashcrumb** [comment]
Now that you mention it, I really need to get crackin' and fix up the other pages on http://ui.hawt.io

**Comment by abkieling** [comment]
I can help with other pages too. Just break the work in separate github issues.
The live examples are great, but I feel an explanation about each config option would be important. We could then show some examples with the most important config variations.

**Comment by gashcrumb** [comment]
Oh, I totally agree, ideally I'd love to keep it inline with the example code, especially since we also can use those pages to develop new features and fix bugs as well.
