### ISSUE TITLE
ui.hawt.io - Improve top-level categories

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio-ui#28]
To help make hawtio-ui better documented, maybe we need to organize all the UI widgets into better top-level categories so it's easier to browse the site, rather than 'blob of widgets 1' and 'blob of widgets 2' :-)

**Comment by abkieling** [comment]
I understand. Will have a look at them and see if I can suggest something.

**Comment by abkieling** [comment]
The widgets being maintained have been placed in the vertical navigation menu.
