### ISSUE TITLE
zero clipboard directive doesn't seem to work

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio-ui#29]
Might be worth tracking down a third-party replacement and alias the existing directive name perhaps?

Might also be worth figuring out if it's a packaging/dependency issue when the site is build, as we need to ensure the .swf file is included in any downstream consumer of the widget.

**Comment by abkieling** [comment]
I'll work on this one. Github has a "Copy to clipboard" button in the clone repo popover. We could check how they implemented it.

**Comment by gashcrumb** [comment]
Great!  I think we're using the github widget actually, I think we just might not be loading the .swf file properly.  The other tricky bit is ensuring that the .swf file will get picked up at the right path by downstream components using `hawtio-ui`.  That being said if there's a better approach that doesn't require the flash it might be worth switching to that...

**Comment by abkieling** [comment]
I did some research and it looks like the way forward is using native browser support via `document.execCommand("copy")`. It might be simple to implement it ourselves. Alternatively, we could use [clipboardjs](https://clipboardjs.com/).
Some references:
https://hacks.mozilla.org/2015/09/flash-free-clipboard-for-the-web/
https://developers.google.com/web/updates/2015/04/cut-and-copy-commands

**Comment by gashcrumb** [comment]
Ah, perfect!  I'd be fine either way, if we can keep the directive
config/usage working the same as the example there then I think we'd be in
great shape...

On Mon, Jul 18, 2016 at 8:49 AM, Alexandre Kieling <notifications@github.com

**Comment by abkieling** [comment]
Just a quick question: `hawtio-ui` defines the `AngularJS` dependency as `"angular": ">= 1.1.0 <= 1.6.0"`. Does it mean features not present in version 1.1.0 cannot be used? It would be nice to use Angular's 1.5.x `.component()` method.

**Comment by gashcrumb** [comment]
I've kept it fairly wide up to this point just for compatibility reasons
but honestly I see no reason not to move to angularjs 1.5 across all hawtio
components, can always go through and fix issues as they come up.

On Mon, Jul 18, 2016 at 9:12 AM, Alexandre Kieling <notifications@github.com

**Comment by abkieling** [comment]
I've just tested it and it's working on http://ui.hawt.io
I think it's safer to leave this one alone and create a new component without flash. The current one checks for a `useCallback` attribute and invokes the callback passing a reference to the ZeroClipboard object. I don't want to break code that depends on that.

**Comment by abkieling** [comment]
We can replace ZeroClipboard if removing the `useCallback` attribute won't break any code. This callback is leaking the encapsulation.

**Comment by abkieling** [comment]
I was waiting for some feedback on this one. Is deprecating this widget and building a new one too much trouble? I didn't want to risk breaking something due to the exposed ZeroClipboard instance via callback.

**Comment by gashcrumb** [comment]
Sorry for the delay!  Yeah, I see it's actually working on the site so that's awesome.  I think deprecating this widget is the way to go, we can then eventually move code that's currently using it to whatever we decide to use?

Had a grep through most of the repos, the `useCallback` seems to be only used in hawtio 1.x code, I don't see it getting used in any current 2.x views.

**Comment by abkieling** [comment]
The project needs a new component that doesn't depend on Flash.
https://chrome.googleblog.com/2016/08/flash-and-chrome.html

**Comment by abkieling** [comment]
So this component works but depends on Flash. Shall we close this issue and deprecate the component? I think there are existing clipboard components we can use.

**Comment by gashcrumb** [comment]
+1 we should mark it deprecated on the site and suggest an alternative.

On Fri, Jan 20, 2017 at 9:04 AM, Alexandre Kieling <notifications@github.com
