### ISSUE TITLE
we should maybe log a warning with `hawtio-simple-table` if there is no `config.primaryKeyFn`

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-ui#3]
I just got myself really confused; the entities in the table didn't have any of these properties (id / _id / name) 
https://github.com/hawtio/hawtio-ui/blob/73be97154f86524b5c61bd6ff0b250a43fd60ce7/plugins/datatable/ts/simpleDataTable.ts#L17

and so selection was all wonky & I thought there were bugs in the table!

If a primary key cannot be found for an entity we should log a warning - along with a warning that maybe the user should supply a function on the config for `primaryKeyFn` to return the primary key for the entity

**Comment by abkieling** [comment]
What do you think about not rendering the table until all mandatory config properties are specified? An error message could be logged informing the missing properties.

**Comment by jstrachan** [comment]
I wonder if it should be a warning; the defaults if there is no function is ok. But then it's a strange bug if you don't supply one & the object doesn't have an _id or key property!

I wonder if we could check if there's no function & the objects don't have an _id / key property we fail with a nice error message?

Btw it'd be also good to ensure that the defaults or function does return a valid unique value - otherwise things go strange. Eg selection tends to select all rows ;)

**Comment by abkieling** [comment]
I could work on this one next. What should exactly happen when there is no primary key? I guess writing an error to the console makes sense. I'm not sure about the UI.

**Comment by gashcrumb** [comment]
Yeah, that's a tough one.  I guess there's two options, just pick the first column definition name and forge ahead even though it could have issues.  Or raise an error, could even render an error in place of the table so it's super-obvious there's a config issue, which should hopefully get our attention if a view is broken :-)

**Comment by alexkieling** [comment]
I changed the default primary key function to use a fallback value composed of the concatenation of all property values and it works fine. Do you think that's a good solution?

**Comment by abkieling** [comment]
Do you think concatenating all property values would hurt performance? It could be the fallback data.

**Comment by gashcrumb** [comment]
I think having the error is probably better, as it's usually not a problem to go and add an id/key to the data, or supply the primaryKeyFn...
