### ISSUE TITLE
ui.hawt.io - Need documentation/page for the tree plugin

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio-ui#31]
Would be good to have some documentation and an example for the tree plugin.

**Comment by abkieling** [comment]
I'm working on this one.

**Comment by abkieling** [comment]
I'm getting the following error:
`Error: [$injector:unpr] Unknown provider: workspaceProvider <- workspace <- hawtioTreeDirective`
What is this `workspace` dependency that gets injected into the directive?

One more thing, I couldn't find any example of building a tree using the Folder class. Where can I find one?

**Comment by gashcrumb** [comment]
Ah, 'workspace' is from hawtio-jmx we'll need to figure out how to get rid
of that service dependency.  Also, I think Folder is an interface we
decided that matches the object you get back from dynatree.

Bear with me a bit, am on vacation until next week...

**Comment by abkieling** [comment]
`workspace` is only referenced on line 136 and only gets executed when the `onSelect` attribute isn't specified. hawtio-jmx could pass a callback via that attribute instead of injecting `workspace`.

**Comment by gashcrumb** [comment]
Yeah, that's totally worth fixing in hawtio-jmx so we can get rid of that
reference.

On Aug 31, 2016 8:28 PM, "Alexandre Kieling" notifications@github.com
wrote:

workspace is only referenced on line 136 and only gets executed when the
onSelect attribute isn't specified. hawtio-jmx could pass a callback via
that attribute instead of injecting workspace.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/hawtio/hawtio-ui/issues/31#issuecomment-243942130, or mute
the thread

**Comment by abkieling** [comment]
I suggest fixing [#21](https://github.com/hawtio/hawtio-jmx/issues/21) and [#48](https://github.com/hawtio/hawtio-ui/issues/48) before doing this one.

**Comment by abkieling** [comment]
The tree plugin has been replaced with patternfly-bootstrap-treeview.
