### ISSUE TITLE
ui.hawt.io - Add pages for undocumented widgets

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio-ui#32]
There's a few widgets that aren't currently documented at all, think this is all of 'em:
- dragDrop.ts
- fileDrop.ts
- filter.ts
- gridster.ts
- groupBy.ts
- list.ts
- object.ts
- pane.ts
- row.ts
- toc.ts
- windowHeight.ts
- tablePager.ts
- tagList.ts I think?

Be good to either get pages for 'em or evaluate if they're still used and maybe zap 'em if not.

**Comment by gashcrumb** [comment]
Got tablePager.ts

**Comment by abkieling** [comment]
All widgets being maintained have documentation.
