### ISSUE TITLE
concatenate third-party .js and .css files into hawtio-ui.js/hawtio-ui.css

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio-ui#33]
This will probably need to be done across a few hawtio projects, but basically bower is complaining about having multiple files in our bower.json:

```
bower invalid-meta  The "main" field has to contain only 1 file per filetype; found multiple .css files: ["dist/OpenSans.css","dist/DroidSansMono.css","dist/ui.dynatree.css","dist/dynatree-icons.css","dist/hawtio-ui.css"]
bower invalid-meta  The "main" field has to contain only 1 file per filetype; found multiple .js files: ["dist/jquery-ui.custom.js","dist/ui-bootstrap.js","dist/ui-bootstrap-tpls.js","dist/transition.js","dist/dialog.js","dist/modal.js","dist/jquery.jsPlumb-custom.js","dist/jquery.dynatree.js","dist/marked.js","dist/d3.js","dist/tabbable.js","dist/hawtio-ui.js"]
```

Why this should matter now when it's been working fine is beyond me, but I'd expect this to start breaking at some point.  Perhaps we need to move third-party deps to say a 'third-party' directory and then just adjust the build to concatenate them into dist/hawtio-ui.js before the typescript-generated code.

Might also be good to see if we can pare down any third-party dependencies we've been inlining in our own package.

**Comment by abkieling** [comment]
As far as I understand, all third-party dependencies should be listed in the `dependencies` section of the `bower.json` file. I see that some third-party dependencies are being copied to the dist folder, e.g. `d3`. As the message says, the `main` section should list only one file per filetype and it shouldn't be minified ([see docs](https://github.com/bower/spec/blob/master/json.md#main).

We could just list `dist/hawtio-ui.js` and `dist/hawtio-ui.css`. Everything else we try to list as dependencies and stop copying to the `dist` folder.  Files that aren't bower packages continue as they are but we stop listing them in the `main` section.

What do you think? Does it make sense?

**Comment by gashcrumb** [comment]
Yeah, so other .js files under dist/ are inlined dependencies, usually because they didn't have proper (or any) bower packaging.  Occasionally I take a look and see if we can get rid of some of them, though a couple are some old legacy bits that are still used in various views.

If we remove 'em without using bower packages that don't have the appropriate `main` attribute set up we'll wind up breaking a few views, especially in `hawtio-jmx` and `hawtio-integration`.

**Comment by abkieling** [comment]
Just to confirm, let's try to move the files under dist/ that are available as bower packages to the bower dependencies section? What do you think we should do with the other ones: leave them as they are or concatenate them with hawtio-ui.js and hawtio-ui.css?

**Comment by gashcrumb** [comment]
Yep, if there's bower packages for any of those files we should try and move to them.  I figure for any leftover files we'd move them into a `vendor` or `third-party` directory, then they'd be concatenated into `dist/hawtio-ui.js` as part of the build, so eventually `dist` will just have generated code.

**Comment by abkieling** [comment]
There is a `jquery-ui.custom.js`, which `jquery.dynatree.js` depends on. I think `jquery.dynatree` can become a bower dependency, but I'm not sure what to do with `jquery-ui.custom.js`.

**Comment by gashcrumb** [comment]
I wonder if this one would fit the bill -> https://github.com/components/jqueryui

As I recall, I just brought that file over from hawtio 1.x, I think the idea was to kind of avoid bringing in too much of the jquery UI stuff when dynatree first got introduced.
