### ISSUE TITLE
add an attribute to specify a maximum tbody height

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-ui#4]
which could then use some JS to set things correctly on the table to allow scrolling of the table body but leaving the headers fixed.

example of how to do it here:
http://stackoverflow.com/a/17380697/2068211

looks like using width calculations and JS might help

**Comment by abkieling** [comment]
Hi all. I will restart my contributions to hawtio with this feature. Is that OK?

**Comment by gashcrumb** [comment]
@alexkieling Sounds great!

**Comment by abkieling** [comment]
What browser versions need to be supported?

**Comment by gashcrumb** [comment]
Chrome, Firefox, edge would be good, probably ie11 I guess...

**Comment by abkieling** [comment]
jQuery [DataTables](https://datatables.net/examples/basic_init/scroll_y.html) puts the scrollbar on the outside. [ng-grid](https://angular-ui.github.io/ui-grid/) and [UI Grid](http://ui-grid.info/) put the scrollbar on the inside, which seems to be the more common way. Any preference?

**Comment by gashcrumb** [comment]
Think inside the table in the tbody element would make the most sense to me
at least...

On Sun, Jun 12, 2016 at 3:26 PM, Alexandre Kieling <notifications@github.com

**Comment by abkieling** [comment]
The strategy provided in stackoverflow get us really close but the header borders and body borders don't align perfectly. I will try to follow other strategy, such as using flex layout or breaking the table in two.
