### ISSUE TITLE
Remove hawtio-slideout directive?

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio-ui#40]
I don't think it's used in any hawtio 2.x code anymore, and it tends to have screen layout issues, nor is it responsive.  Wonder if it's time to get rid of this one?

**Comment by gashcrumb** [comment]
Ah, it's used in hawtio-integration in a couple spots:

```
C:\Source\hawtio-integration\plugins\activemq\html\durableSubscribers.html
C:\Source\hawtio-integration\plugins\camel\html\browseEndpoint.html
C:\Source\hawtio-integration\plugins\camel\html\debug.html
C:\Source\hawtio-integration\plugins\camel\html\traceRoute.html
```

But would be easy to remove.

**Comment by abkieling** [comment]
What UI component do you think we could use instead of the hawtio-slideout? Ideally, it would be something available in PatternFly or UI Bootstrap.

**Comment by abkieling** [comment]
We could replace the slide component with a modal. What do you think?

**Comment by gashcrumb** [comment]
hmm, it'd be a big modal potentially, I think some pages that use the slideout are like the camel debugger which has a table in there etc.

That being said in these cases a controller could maybe use a tab, or expander thingie or any number of other approaches to managing it's content.  Or a modal if it's suitable :-)

**Comment by abkieling** [comment]
I'm changing the Camel plugin - Browse endpoint message to a modal and it's looking good. I agree that the camel debugger might not work well with a modal. We could try to simulate a debug panel similar to the ones we have on IDEs.
