### ISSUE TITLE
Upgrade AngularJS to 1.5.x

### ISSUE THREAD

**Issue by abkieling** [hawtio/hawtio-ui#46]
Upgrade AngularJS to 1.5.x so we can start using the `.component()` method and follow a style of application architecture more inline with Web Components and Angular 2.
Reference: https://docs.angularjs.org/guide/component

**Comment by gashcrumb** [comment]
+1 we'll need to be mindful that templates in downstream components will need to be updated, such as [hawtio-jmx](https://github.com/hawtio/hawtio-jmx), [hawtio-integration](https://github.com/hawtio/hawtio-integration), and I'm sure I'm forgetting other hawtio-\* projects.  Should mostly be a matter of search/replace, probably worth cutting components over in batches perhaps?

**Comment by abkieling** [comment]
Yep, all downstream projects will need to be checked. There is some documentation about migrating to new versions: https://docs.angularjs.org/guide/migration

**Comment by abkieling** [comment]
I noticed the AngularJS version has been defined as 1.5.x. Great stuff! Is everything working well?

**Comment by abkieling** [comment]
This upgrade has been done so I'm closing the issue.
