### ISSUE TITLE
How should I create a demo environment?

### ISSUE THREAD

**Issue by xingsd163** [hawtio/hawtio-ui#49]
Hello!
How should I create a demo environment, just like http://ui.hawt.io/docs/welcome?main-tab=docs&sub-tab=docs-welcome?

Could you please give a basic guide? Thanks.

**Comment by gashcrumb** [comment]
Yeah, the readme is totally missing a link to [this document](https://github.com/hawtio/hawtio/blob/master/docs/Overview2dotX.md) let me add that.  Also after you run `gulp` you just need to point your browser at http://localhost:2772.  I'll do the same for `hawtio-dashboard` as well.

**Comment by gashcrumb** [comment]
Added those links, should be all set, thanks!

**Comment by abkieling** [comment]
@xingsd163 can we close this issue?

**Comment by xingsd163** [comment]
@alexkieling Yes. Thank you!!
