### ISSUE TITLE
Remove deprecated components for 3.x line

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-ui#52]
Let's remove deprecated components such as:

- Zero Clipboard
- Icons
- Breadcrumbs
- (and maybe more?)

so that we can make sure we use the preferred PatternFly components.

**Comment by tadayosi** [comment]
OK, it looks like we decided to leave them as is for 3.x line at #29?  Then let's remove them at 4.x line (in the future) and just make sure we don't use them at downstream components.

**Comment by tadayosi** [comment]
Discussed with @alexkieling and we've decided to go ahead to remove the deprecated components in 3.x.

**Comment by abkieling** [comment]
I've added a "deprecated" alert message to each component I think we have a better alternative elsewhere. We need to make sure other hawtio-* 3.x projects don't use the deprecated components before removing them.

**Comment by tadayosi** [comment]
As far as I checked `hawtio-breadcrumbs` and `hawtio-icon` were not used from any hawtio-* 3.x projects, so it should be safe to have been removed. I'll incrementally remove other deprecated ones after checking there are indeed no usages anywhere.

**Comment by abkieling** [comment]
@tadayosi  I believe this issue can be closed.

**Comment by tadayosi** [comment]
Yep, closing.
