### ISSUE TITLE
Sorting isn't working for regular columns in the hawtio-simple-table

### ISSUE THREAD

**Issue by abkieling** [hawtio/hawtio-ui#6]
In the hawtio-simple-table, sorting isn't working for columns that don't specify custom sorting.
In the following URL, the Name, City, and Twitter columns are not getting sorted:
http://ui.hawt.io/datatable/test?main-tab=datatable-test

I have a fix for this issue and will send a PR as soon as possible.

**Comment by davsclaus** [comment]
Yay sounds cool you are digging into the code and help.
